language: cpp
cache:
  directories:
  - $HOME/.stack
before_install:
  - sudo apt-get install -y z3
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack exec cabal install liquidhaskell
install:
  - stack --no-terminal --skip-ghc-check setup
script:
  - stack exec liquid src/Ex2.hs
  - stack exec liquid src/Ex3.hs
addons:
  apt:
    update: true
