dist: xenial
language: c

cache:
  directories:
  - $HOME/.stack
before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - stack --no-terminal --skip-ghc-check setup
  - cabal update
  - cabal install liquidhaskell
script:
  - stack exec liquid src/Ex2.hs
  - stack exec liquid src/Ex3.hs
  - stack exec liquid src/Ex4.hs
addons:
  apt:
    packages:
    - z3
    - cabal-install-2.2
    - ghc-8.4.3
    sources:
    - hvr-ghc
