dist: xenial
language: c
cache:
  directories:
  - $HOME/.stack
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - git clone --recursive https://github.com/ucsd-progsys/liquidhaskell ~/liquidhaskell
  - cd ~/liquidhaskell && stack install
  - cd ${TRAVIS_BUILD_DIR}
  - stack --no-terminal --skip-ghc-check build
script:
  - stack exec liquid src/Ex2.hs
  - stack exec liquid src/Ex3.hs
  - stack exec liquid src/Ex4.hs
  - stack exec liquid src/Ex42.hs
  - stack exec liquid src/Ex05.hs
addons:
  apt:
    packages:
    - z3
