dist: xenial
language: cpp
ghc:
  - 8.4.3
cache:
  directories:
  - $HOME/.stack
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - stack --no-terminal --skip-ghc-check setup
  - cabal install liquidhaskell
script:
  - stack exec liquid src/Ex2.hs
  - stack exec liquid src/Ex3.hs
addons:
  apt:
    packages:
    - z3
