dist: xenial
language: haskell
ghc:
- 8.4.3
cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - cabal update
  - cabal install liquidhaskell
  - stack --no-terminal --skip-ghc-check setup
script:
  - stack exec liquid src/Ex2.hs
  - stack exec liquid src/Ex3.hs
  - stack exec liquid src/Ex4.hs
addons:
  apt:
    packages:
    - z3